openapi: 3.0.3
info:
  title: MasterNodeProject - OpenAPI 3.0
  description: |-
    This is documention!
  version: 1.0.11
servers:
  - url: http://localhost:7800/api/v1
  - url: https://localhost:7800/api/v1
tags:
  - name: Auth
    description: Everything about Auth
  - name: User
    description: Everything about User
