openapi: 3.0.3
info:
  title: MasterNodeProject - OpenAPI 3.0
  description: |-
    This is documention!
  version: 1.0.11
servers:
  - url: http://localhost:7800/api/v1
  - url: https://localhost:7800/api/v1
tags:
  - name: Auth
    description: Everything about Auth
  - name: User
    description: Everything about User
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: User Login
      description: User Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/register:
    post:
      tags:
        - Auth
      summary: User Register
      description: User Register
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
          format: string
        lastName:
          type: string
          format: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        avatar:
          type: object
          properties:
            url:
              type: string
        address:
          type: object
          properties:
            address1:
              type: string
            address2:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            country:
              type: string
      required:
        - email
        - password
        - firstName
        - lastName
    Error:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
        multipleErrors:
          type: array
          items:
            type: object
        success:
          type: boolean
      required:
        - message
